### ISSUE TITLE
One of the earliest paper for VIF in deep learning

### ISSUE THREAD

**Issue by zzowenzz** [xingchenzhang/Visible-infrared-image-fusion-based-on-deep-learning#1]
Hi @xingchenzhang, really appreciate your review paper on PAMI. 
May I ask that why don't you view **DenseFuse**, which published on TIP 2018 as one of the earliest papers using deep learning in VIF? It is one year earlier than the one using NSST and deep Boltzmann machine in 2019.

**Comment by xingchenzhang** [comment]
> Hi @xingchenzhang, really appreciate your review paper on PAMI. May I ask that why don't you view **DenseFuse**, which published on TIP 2018 as one of the earliest papers using deep learning in VIF? It is one year earlier than the one using NSST and deep Boltzmann machine in 2019.

Hi, 

Thank you for your comment. 

Yes, DenseFuse is a very early work in this field, but the paper "Visible and infrared image fusion using NSST and deep Boltzmann machine" by Wei Wu et al. (https://www.sciencedirect.com/science/article/pii/S0030402617315073) was published earlier than DenseFuse. 

Best wishes,
Xingchen

**Comment by zzowenzz** [comment]
Hi @xingchenzhang, thanks for your reply. I looked at this paper, and it seems that this one is using NSST to extract features at different scales with different directions and DBM to select the coefficients.
